---
- name: Netbox Demo Create Tenant
  connection: local
  hosts: localhost
  gather_facts: no
  vars_files:
    - default_vars.yml

  tasks:
    - name: Create site within Netbox with only required information
      netbox.netbox.netbox_tenant:
        netbox_url: "{{ NETBOX_URL }}"
        netbox_token: "{{ NETBOX_API_KEY }}"
        data:
          name: Test - Joon Tenant Demo
        state: present
