---
- name: Netbox Demo Create Site
  connection: local
  hosts: localhost
  gather_facts: no
  vars_files:
    - default_vars.yml

  tasks:
    - name: Create site within Netbox with only required information
      netbox.netbox.netbox_site:
        netbox_url: http://192.168.1.35:8000
        netbox_token: 802d28ad644ba97702a3bf8a34e081b1fd0669fe
        data:
          name: Test - Joon Site Demo
        state: present
